name: Build & Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE: unganisha/oci-linux

jobs:
  build:
    name: "Build and/or Publish Java ${{ matrix.java_version }} Image"
    strategy:
      matrix:
        java_version: [11, 17]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: ${{ (github.event_name != 'pull_request') && (github.repository == env.IMAGE) }}
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}

      - name: Build JDK ${{ matrix.java_version }}
        id: publish
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ (github.event_name != 'pull_request') && (github.repository == env.IMAGE) }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: JDK_VERSION=${{ matrix.java_version }}
          tags: |
            ${{ env.IMAGE }}:${{ matrix.java_version }}
            ${{ env.IMAGE }}:${{ matrix.java_version }}.${{ github.run_number }}
